name: Steno_Game
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  dartz: ^0.10.1
  firebase_auth: ^4.15.0
  firebase_core: ^2.22.0
  cloud_firestore: ^4.15.4
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  google_fonts: ^6.1.0
  json_annotation: ^4.8.1
  stacked: ^3.4.0
  stacked_services: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/png/


