// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRpVornzafIfciQRomMKh-qKRJPF3fX3w',
    appId: '1:181073997803:web:ea0632514a8ab14f15f3ae',
    messagingSenderId: '181073997803',
    projectId: 'steno-game',
    authDomain: 'steno-game.firebaseapp.com',
    storageBucket: 'steno-game.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoV57OlFzceoGBE-Nbnw5o8_6FlqarmPE',
    appId: '1:181073997803:android:9a4d8c877ec24bae15f3ae',
    messagingSenderId: '181073997803',
    projectId: 'steno-game',
    storageBucket: 'steno-game.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9K9PeaGle9HjvsMVBxIf_ivEX2pnxOJc',
    appId: '1:181073997803:ios:d73761eefbcfbc0b15f3ae',
    messagingSenderId: '181073997803',
    projectId: 'steno-game',
    storageBucket: 'steno-game.appspot.com',
    iosBundleId: 'com.example.stenoGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9K9PeaGle9HjvsMVBxIf_ivEX2pnxOJc',
    appId: '1:181073997803:ios:20a598570d316eae15f3ae',
    messagingSenderId: '181073997803',
    projectId: 'steno-game',
    storageBucket: 'steno-game.appspot.com',
    iosBundleId: 'com.example.stenoGame.RunnerTests',
  );
}
